server.port=${PORT:5454}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/online_food}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
server.error.include-message=always

stripe.api.key=${STRIPE_API_KEY}

jwt.secret.key=${JWT_SECRET_KEY:9f3d7c1a2b6e4f58a0d9c3b7e1f4a6d82c5b9e0f3a7d1c4b8e2f6a9d0c3b7e51}